### ISSUE TITLE
Unknown country code "JL"

### ISSUE THREAD

**Issue by p4nther93** [Dirble/api-doc#1]
Hi,

the api request http://api.dirble.com/v2/countries?token={my token} returns, among others, the country code "JL" ( {"country_code":"JL","continent_id":2} ). I can't find this code anywhere, so I assume it is a bug.

Regards,
Christian

**Comment by confact** [comment]
@christian1993 Thanks! It is removed. I think I would need to update the country list and remove weird country codes.

Thanks for the find once again and sorry for the slow response!
