### ISSUE TITLE
Countries output seems to have changed.

### ISSUE THREAD

**Issue by adamcik** [Dirble/api-doc#4]
`/v2/countries` is documented as: `[{"country_code": "DZ", "Continent_id": 3}, ...]` but seems to now be `[{"name":"Andorra","country_code":"AD","region":"Europe","subregion":"Southern Europe"}, ...]`

This has broken mopidy-dirble clients per https://github.com/mopidy/mopidy-dirble/issues/11  I would recommend adding bad the `Continent_id` field back, as removing fields from a published API isn't great for clients.

In the meantime I intend to release a new version making use of the extended data. But since we have this packaged in Debian and have no control of when people update there is no knowing how long how long old clients will be around...

**Comment by confact** [comment]
@adamcik I am sorry. This was removed when I migrated to a third party dataset, so it is not in a database so I can not connect to a continent_id anymore.

**Comment by confact** [comment]
@adamcik but i agree. I shall not remove fields at all. This was a mistake on my part. I think i send out a email about the change but that doesn't help you.

Again, sorry man.
I will do proper next time.

**Comment by adamcik** [comment]
Np, thanks for the quick followup. We have a new version of Mopidy-Dirble out now that uses the country names you added and uses the lookup country by continent endpoint.

So hopefully people upgrade quickly. Also note that we set the user-agent so if want to gauge the number of old clients just look for pre 1.2.0 versions in your logs :-)
